/**
 * Build-time generator for the Material 3 color tokens.
 *
 * Run with `npm run gen:tokens`. It bundles through esbuild (the library ships
 * bundler-oriented ESM) and writes a fully static `src/theme/tokens.ts` — the app
 * runtime never imports `@material/material-color-utilities`, so there is zero
 * runtime dependency. Re-run this only when a seed below changes.
 *
 * Seeds (from Epic 9 decisions):
 *   - primary/brand: teal `#00696E`
 *   - secondary/support: Payne's grey `#536878` (a desaturated blue-grey — fits MD3's
 *     intentionally low-chroma secondary register while reading as its own hue)
 *   - tertiary/accent: a complementing amber-yellow (hue ~80)
 */
import { CorePalette, Hct, TonalPalette, argbFromHex, hexFromArgb } from '@material/material-color-utilities'
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'

const SEED = '#00696E'
const SECONDARY_SEED = '#536878'
const TERTIARY_HUE = 80
const TERTIARY_CHROMA = 50

// Backgrounds/surfaces carry the brand hue rather than reading as plain white/grey. MD3's default
// "tonal spot" neutrals are near-zero chroma (4/8); we raise them so every surface tone is a soft
// teal-tinted neutral in both modes. Keep these gentle — too much chroma muddies the surfaces.
const NEUTRAL_CHROMA = 16
const NEUTRAL_VARIANT_CHROMA = 24
const primaryHue = Hct.fromInt(argbFromHex(SEED)).hue

const core = CorePalette.of(argbFromHex(SEED))
const secondary = TonalPalette.fromInt(argbFromHex(SECONDARY_SEED))
const tertiary = TonalPalette.fromHueAndChroma(TERTIARY_HUE, TERTIARY_CHROMA)

// MD3 tonal palettes. CorePalette gives primary/error from the seed; we override secondary
// (Payne's grey), tertiary (amber), and the two neutral ramps (teal-tinted, above).
const P = core.a1
const S = secondary
const N = TonalPalette.fromHueAndChroma(primaryHue, NEUTRAL_CHROMA)
const NV = TonalPalette.fromHueAndChroma(primaryHue, NEUTRAL_VARIANT_CHROMA)
const E = core.error
const T = tertiary

const h = (pal: TonalPalette, tone: number) => hexFromArgb(pal.tone(tone))

// role -> [palette, lightTone, darkTone]. The surface-container ladder is mapped from the
// neutral palette ourselves (the legacy `schemes` object omits it).
const ROLES = {
  primary: [P, 40, 80],
  onPrimary: [P, 100, 20],
  primaryContainer: [P, 90, 30],
  onPrimaryContainer: [P, 10, 90],
  secondary: [S, 40, 80],
  onSecondary: [S, 100, 20],
  secondaryContainer: [S, 90, 30],
  onSecondaryContainer: [S, 10, 90],
  tertiary: [T, 40, 80],
  onTertiary: [T, 100, 20],
  tertiaryContainer: [T, 90, 30],
  onTertiaryContainer: [T, 10, 90],
  error: [E, 40, 80],
  onError: [E, 100, 20],
  errorContainer: [E, 90, 30],
  onErrorContainer: [E, 10, 90],
  background: [N, 98, 6],
  onBackground: [N, 10, 90],
  surface: [N, 98, 6],
  onSurface: [N, 10, 90],
  surfaceVariant: [NV, 90, 30],
  onSurfaceVariant: [NV, 30, 80],
  surfaceDim: [N, 87, 6],
  surfaceBright: [N, 98, 24],
  surfaceContainerLowest: [N, 100, 4],
  surfaceContainerLow: [N, 96, 10],
  surfaceContainer: [N, 94, 12],
  surfaceContainerHigh: [N, 92, 17],
  surfaceContainerHighest: [N, 90, 22],
  outline: [NV, 50, 60],
  outlineVariant: [NV, 80, 30],
  shadow: [N, 0, 0],
  scrim: [N, 0, 0],
  inverseSurface: [N, 20, 90],
  inverseOnSurface: [N, 95, 20],
  inversePrimary: [P, 80, 40],
} as const satisfies Record<string, readonly [TonalPalette, number, number]>

type Role = keyof typeof ROLES

const scheme = (which: 'light' | 'dark') => {
  const idx = which === 'light' ? 1 : 2
  const out: Record<string, string> = {}
  for (const [role, spec] of Object.entries(ROLES)) out[role] = h(spec[0], spec[idx] as number)
  return out as Record<Role, string>
}

const light = scheme('light')
const dark = scheme('dark')

const fmt = (s: Record<Role, string>) =>
  Object.entries(s)
    .map(([k, v]) => `  ${k}: '${v}',`)
    .join('\n')

const body = `// AUTO-GENERATED by scripts/gen-md3-tokens.ts — do not edit by hand.
// Regenerate with \`npm run gen:tokens\`. Seed: ${SEED} (teal), tertiary: amber-yellow (hue ${TERTIARY_HUE}).

export interface Md3Scheme {
${(Object.keys(ROLES) as Role[]).map((r) => `  ${r}: string`).join('\n')}
}

export const lightScheme: Md3Scheme = {
${fmt(light)}
}

export const darkScheme: Md3Scheme = {
${fmt(dark)}
}
`

const out = join(process.cwd(), 'src/theme/tokens.ts')
writeFileSync(out, body)
console.log(`Wrote ${out}`)
console.log(`  light.primary=${light.primary}  light.tertiary=${light.tertiary}  dark.surface=${dark.surface}`)
